[desktop]
  secret_key=impacta-hue-lab-secret-key-2024
  allowed_hosts=*
  default_hdfs_superuser=hdfs
  django_debug_mode=false
  log_level=WARNING

  [[database]]
    engine=django.db.backends.sqlite3
    name=/tmp/desktop/desktop.db

  [[auth]]
    # Permite que o primeiro usuário a acessar vire administrador
    backend=desktop.auth.backend.AllowFirstUserDjangoBackend

[filebrowser]
  show_download_button=true

[hadoop]

  [[hdfs_clusters]]
    [[[default]]]
      fs_defaultfs=hdfs://namenode:9000
      webhdfs_url=http://namenode:9870/webhdfs/v1
      hadoop_conf_dir=/etc/hadoop/conf
      logical_name=namenode

  [[yarn_clusters]]
    [[[default]]]
      resourcemanager_host=resourcemanager
      resourcemanager_port=8032
      resourcemanager_api_url=http://resourcemanager:8088
      proxy_api_url=http://resourcemanager:8088
      history_server_api_url=http://historyserver:8188

[beeswax]
  hive_server_host=hiveserver2
  hive_server_port=10000
  server_conn_timeout=120
  auth_username=hive
  auth_password=

[metastore]
  server_conn_timeout=120
